### ISSUE TITLE
Question regarding `slice` vs `nicer_slicer`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#116]
Here:

https://github.com/COSIMA/regional-mom6/blob/b0e13c5f6a45eec9451ea2165f19ae0fe9176aed/regional_mom6/regional_mom6.py#L1076-L1101

Can't we always use the `nicer_slicer` to simplify things?

Would `nicer_slicer` fail if we don't have a domain that wraps around the globe?

**Comment by ashjbarnes** [comment]
Yes, nicer slicer expects things to wrap around the globe. Hence it does all this shifting to move the 'seam' to the opposite side of the world to your region of interest. That's why we just slice normally for non-global outputs

An assumption here is that if your raw data is already a small regional selection, you don't have a  random seam in the middle, like longitude from -170 to 30. This should be made more explicit

**Comment by ashjbarnes** [comment]
I think this issue is resolved but feel free to reopen if not @navidcy !

**Comment by navidcy** [comment]
Oh now I remembered. I was a bit confused with the ACCESS-OM2 example where `longitude_slicer` is used for a domain that _does not_ wrap all over 360 degrees in longitude. I meant to ask here about that and never did.

**Comment by ashjbarnes** [comment]
The raw ACCESS OM2 output does wrap around the whole world right?

**Comment by ashjbarnes** [comment]
the former. The point of the slicer is to handle when your raw data is 360 degrees and you want to slice it across the 'seam' in the data

**Comment by ashjbarnes** [comment]
you can ONLY use the slicer when your raw data is 360 degrees as this is the underlying assumption for how it shifts the seam around

**Comment by navidcy** [comment]
Gotcha!
