### ISSUE TITLE
Formula for vertical levels?

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#53]
Are the vertical levels here defined recursively?

https://github.com/COSIMA/regional-mom6/blob/abf630d3fa909f0e609eaba167d454419f96e812/regional_mom6/regional_mom6.py#L248-L279

And maximum rate of change of the vertical spacing occurs at the mid-depth (exactly)?

**Comment by navidcy** [comment]
cc @kialstewart

**Comment by navidcy** [comment]
note to self after chatting w @kialstewart: [10.1016/j.ocemod.2017.03.012](https://doi.org/10.1016/j.ocemod.2017.03.012) might be relevant; see section 2

**Comment by ashjbarnes** [comment]
Ok so I took Kial's formula, but modified it so that the free parameter is different. From memory I think you give it number of layers, depth, ratio of the biggest to smallest ratio and then it chooses where to place the first layer.

Vertical levels aren't defined recursively, but the equation is solved by recursively searching for the solution. After I wrote this code I realised that you can solve it directly but it worked and apparently I never bothered changing it.

**Comment by ashjbarnes** [comment]
What would resolve this @navidcy? This is the vertical coordinate that I use for my experiments and so currently is the only one implemented. Future updates will implement more grid generation options - see issue #69 so this one isn't intended to be perfect or one size fits all

**Comment by navidcy** [comment]
A description in the docstring for how these levels are computed?

My problem wasn't that it wasn't as generic as possible. My main issue was that I couldn't understand what was happening.
